### ISSUE TITLE
Location of json-files

### ISSUE THREAD

**Issue by WirthmU** [AllskyTeam/allsky-modules#100]
Currently I am using - besides the standard ones - two modules: light and AllSKY Export. The corresponding json files are located here:

`/home/pi/allsky/config/overlay/extra/allskylight.json`

`/home/pi/allsky/html/allskydata.json`

Since I would want to export those json-files to a server it would be nice to have them all in one directory - in my case in ${ALLSKY_WEBUI}, i.e. /home/pi/allsky/html/.

Is there a way to set this pathway om the light module?

**Comment by Alex-developer** [comment]
Unfortunately not.

The overlay module expects to find any extra data files in /home/pi/allsky/config/overlay/extra

if you were to put the exported data in the same directory the overlay module would try and use the data and it will cause problems.
