### ISSUE TITLE
Use WeatherUnderground data from the Weatherground module for DewControl sensor

### ISSUE THREAD

**Issue by Alex-developer** [AllskyTeam/allsky-modules#124]
### Discussed in https://github.com/AllskyTeam/allsky-modules/discussions/123

<div type='discussions-op-text'>

<sup>Originally posted by **bendenajones** March 29, 2024</sup>
Like for Openweather, support either directly fetching Weatherunderground data or re-using the overlay file produced by the module. I have a weather station that uploads dew point, temp, humidity, etc. and it would be great to leverage that data.</div>

**Comment by Alex-developer** [comment]
@bendenajones I have added support for this, would you be willing to test it?

**Comment by bendenajones** [comment]
yes
