### ISSUE TITLE
Bug module cloud

### ISSUE THREAD

**Issue by ettoreribaudo** [AllskyTeam/allsky-modules#135]
**Describe the bug** random i have this error: ERROR: Module cloud failed on line 251 - module 'board' has no attribute 'I2C'

bus I2c Rasperry is ok.

**To Reproduce**

**Screenshots**

**Allsky Information:**
 - OS: [Bullseye 64bit and Full]
 - Allsky Version: last
 - Pi model: 4b 4 gb ram
 - Camera: innomaker 462

**Sensors**
MLX90614

![i2c](https://github.com/AllskyTeam/allsky-modules/assets/21957407/012341a7-6a4b-457f-a1fb-78071df9fc5c)
![mlx96014](https://github.com/AllskyTeam/allsky-modules/assets/21957407/4e2d6e2e-55e8-4cd4-902e-f389e9503674)

**Comment by ettoreribaudo** [comment]
Please responde .
Ettore

**Comment by Alex-developer** [comment]
Closing as I am responding in the discussion
