### ISSUE TITLE
module allskyAi

### ISSUE THREAD

**Issue by ettoreribaudo** [AllskyTeam/allsky-modules#138]
**Describe the bug**
Last week it worked but now it always gives me fake but the photos are uploaded to the allskyAI.com website

I uninstalled and reinstalled the module but still false

**Expected behaviour**

**Screenshots**

**Allsky Information:**
 - OS: Bullseye
 - Allsky Version: last
 - Pi model: PI4 B 4 GB
 - Camera: imx462 PI
**Sensors**
![ai py](https://github.com/AllskyTeam/allsky-modules/assets/21957407/b51eb229-7e3d-44f9-8cbf-a2c08cfa48b3)

**Comment by ettoreribaudo** [comment]
Nothing response?

**Comment by Alex-developer** [comment]
@TheCrowsNestAstro Can you shed any light on this issue?

**Comment by ettoreribaudo** [comment]
This web is blocked: https://www.allskyai.com/

**Comment by Alex-developer** [comment]
I have spoken to the developer of allskyai and he is looking into the website issue

**Comment by ettoreribaudo** [comment]
Web allskyai.com is ok.

**Comment by Alex-developer** [comment]
Online for me as well - Is the module working now?

**Comment by ettoreribaudo** [comment]
Yes perfect.

**Comment by Alex-developer** [comment]
Thanks will close the issue

**Comment by ettoreribaudo** [comment]
Hello Alex same problems module it is no longer found in the variables.
Ettore
![allskyia](https://github.com/AllskyTeam/allsky-modules/assets/21957407/e1c7afb5-2ef7-4afd-8a56-d1c8fc2fb768)
![Immagine 2024-07-08 181649](https://github.com/AllskyTeam/allsky-modules/assets/21957407/35b1fad7-524f-4693-b4ce-ddf2fe5abcc5)
