### ISSUE TITLE
[Question - Dew Heater Control] When will the dew heater turn back on after reaching the max on time?

### ISSUE THREAD

**Issue by kgabriel-dev** [AllskyTeam/allsky-modules#158]
Hey. I am in the process of building an Allsky camera and want to include a dew heater. I have seen that in your module, I can configure a maximum time for the dew heater to stay on, but I didn't find information about how long it will stay off after that time is reached. Could you tell me if it is possible to configure this, or what the standard behavior is in that case?

**Comment by Alex-developer** [comment]
It will revert back to the standard behaviour after that time
