### ISSUE TITLE
allsky_discordsend do not send images with overlay datas

### ISSUE THREAD

**Issue by drakula1981** [AllskyTeam/allsky-modules#163]
I've Activated the discord send module. 
It works fine and send images at the setted interval.
BUT, when I create images with the legacy overlay datas manager, the final image contains the overlays datas and when I activate the module manager, the image is sent raw, without any overlay datas.

**To Reproduce**
Steps to reproduce the behaviour:
1. Activate the Discord send module and configure it to be able to send daytime and nighttime images to a discord channel
2. Activate the legacy overlay datas manager, setup a legacy data and wait for an image sent to the discord channel, the overlay datas are visible
3. Switch to the module overlay data manager, put some overlay text in the overlay editor, save it and wait for an image sent to the discord channel, the overlay datas aren't visible

**Expected behaviour**
The overlayed image is sent to the channel when the module overlay manager is used

**Screenshots**
With the legacy overlay manager :
![image](https://github.com/user-attachments/assets/73b4fbc1-c7f8-43d7-a0a1-c7d7f9d2ec3b)
With the module overlay manager :
![image](https://github.com/user-attachments/assets/ddf31e54-42be-4a86-b3f6-debb4beb8248)

**Allsky Information:**
 - OS: Bookworm, 64bits lite up to date
 - Allsky Version: v2023.05.01_04
 - Pi model: RaspBerry Pi 5 4GB
 - Camera: Zwo ASI678MC 
 
**Sensors**
BME280 on I2C Address 0x77

**Additional context**
N/A

**Comment by drakula1981** [comment]
I took a look at the allsky_discordsend.py file and I saw this :
![image](https://github.com/user-attachments/assets/000c9a27-3cda-4ca2-aef1-e19e1a7e8f4e)
could it be the part of the problem ?
Thus, I thought that the modules are arranged In the module manager, i put the "discord send" module right after the "overlay datas fields on the image" module as seen in the screenshot below :
![image](https://github.com/user-attachments/assets/75f1a89e-295b-46df-bc5f-e4fdebeb52d4)
But it has no effects

**Comment by Alex-developer** [comment]
This was a deliberate decision by me as I wanted the clean images in Discord.

I'll add an option to send either the clan image or the annotated image

Cheers

Alex

**Comment by Alex-developer** [comment]
Code all done, I am testing it on my pi just to make sure that the end of night discord sends still work. Once i am happy I will merge the code.

If you want to try it before hand its in the 163- branch

Alex

**Comment by drakula1981** [comment]
Hi alex!
Well done!
I´ll give a try on the next days and give you my feedback!
Thanks for your reactivity!

**Comment by Alex-developer** [comment]
This work overnight for my setup so have merged the change into master. If you reinstall the discord module there is an option against day and night to either send the annotated or unannotated image.
