### ISSUE TITLE
Module install problem. 

### ISSUE THREAD

**Issue by clambert24** [AllskyTeam/allsky-modules#177]
Hi. I'm trying to install the github modules as described but it won't install anything. Can you help please. 
![Screenshot_20241111_221634_RaspController](https://github.com/user-attachments/assets/5b1410c7-2e1a-4883-aa50-ed50440f07fa)

**Comment by Alex-developer** [comment]
After the git clone enter

cd allsky-modules

Then run the install, that step is missing from the instructions which I will amend
