### ISSUE TITLE
Allsky modules (Export, Clear Sky) cannot be selected and saved

### ISSUE THREAD

**Issue by WirthmU** [AllskyTeam/allsky-modules#27]
Neither the Export nor the Clear Sky modules can be activated and saved in my configuration. Also the settings are not accessible.
In fact none of the available modules can be selected and saved.

**Comment by Alex-developer** [comment]
What happens when you try to activate them?

**Comment by WirthmU** [comment]
I click on the activation checkbox
The checkbox sign appears
I click on the settings box nothing nothing happens
I save the module by clicking on the green sign icon which turns black
When I leave the modules section and return afterwards the checkbox is no longer activated

**Comment by Alex-developer** [comment]
> I click on the activation checkbox The checkbox sign appears I click on the settings box nothing nothing happens I save the module by clicking on the green sign icon which turns black When I leave the modules section and return afterwards the checkbox is no longer activated

Do you know howto use the browser dev tools? If you open the dev tools and look at he 'console' tab are there any errors display whilst you are trying to get to the settings?

**Comment by WirthmU** [comment]
This is what it looks like:

![image](https://github.com/Alex-developer/allsky-modules/assets/27740335/cae5e18d-cbb2-4f8e-8873-134c2fc63ba1)

**Comment by Alex-developer** [comment]
Those errors are nothing to worry about and won't be causing the issue you have. To be honest I am a little stumped by this one. Its not something I have seen before.

I'll have a think about it !

**Comment by WirthmU** [comment]
Could it be a permission issue? Where are the files located?

**Comment by Alex-developer** [comment]
> Could it be a permission issue? Where are the files located?

Could be they are all in the ~/allsky/config/modules folder.

**Comment by WirthmU** [comment]
This is how the folder looks like:

![image](https://github.com/Alex-developer/allsky-modules/assets/27740335/73b3b1f2-fe1e-447c-a96e-3cc5186691b8)

It seems that there are no modules at all!

**Comment by Alex-developer** [comment]
> This is how the folder looks like:
> 
> ![image](https://user-images.githubusercontent.com/27740335/280631995-73b3b1f2-fe1e-447c-a96e-3cc5186691b8.png)
> 
> It seems that there are no modules at all!

They look fine. These are the files that store the module settings and if the permissions on these were wrong it would fail to save but they are fine

Still stumped :-(

**Comment by WirthmU** [comment]
The problem has been solved. It was an error on my side. I should have read the manual where its clearly written that to activate any module it has to be dragged to the active ones, which I did not.
Thank you for your support!
