### ISSUE TITLE
Fritzing image for dewheater is wrong

### ISSUE THREAD

**Issue by starhopper-de** [AllskyTeam/allsky-modules#3]
I think the Fritzing schematic for the dewheater module ist wrong. I2C-Bus wires for SDA and SCL are mixed up.
[https://raw.githubusercontent.com/thomasjacquin/allsky/master/html/documentation/modules/dew-heater.png](url)
This should by right:
![Bildschirmfoto vom 2023-05-21 08-08-12](https://github.com/Alex-developer/allsky-modules/assets/44210083/8e14ef1a-08e2-4b6d-bff4-70f263bd1430)

**Comment by Alex-developer** [comment]
Thanks I'll update the image

**Comment by Alex-developer** [comment]
This has been fixed in the main allsky repo, currently in the dev branch
