### ISSUE TITLE
Influxdb installation

### ISSUE THREAD

**Issue by Daviddb35** [AllskyTeam/allsky-modules#7]
Hi,

the installation instruction are no longer available, new instructions from:

https://www.influxdata.com/blog/linux-package-signing-key-rotation/?_gl=1*1t2eak4*_ga*NjE4MTg5Mzc2LjE2ODY2ODEyNjY.*_ga_CNWQ54SDD8*MTY4ODg0MzI0MS44LjEuMTY4ODg0NDMzMC41NC4wLjA.

- wget -q https://repos.influxdata.com/influxdata-archive_compat.key
- gpg --with-fingerprint --show-keys ./influxdata-archive_compat.key
- cat influxdata-archive_compat.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null
- echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list
- sudo rm -f /etc/apt/trusted.gpg.d/influxdb.gpg

David

**Comment by Alex-developer** [comment]
Thanks I'll update the notes

Appreciate the feedback
